############# English navigation ##############

[[main]]
name = "About me"
url = "about/"
weight = 1

[[main]]
name = "Résumé"
url = "elements/"
weight = 2

[[main]]
weight = 4
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Blog"
url = "/"

[[main]]
parent = "Pages"
name = "Contact"
url = "contact/"

[[main]]
parent = "Pages"
name = "Authors"
url = "/"

[[main]]
parent = "Pages"
name = "Categories"
url = "/"


[[main]]
parent = "Pages"
name = "Notes"
url = "notes/"

# footer menu
[[footer]]
name = "How did you build this Swapnil ?"
url = "how/"
weight = 1

